/* GET CUSTOMERS */
export const GET_LEARNERS_LIST = "GET_LEARNERS_LIST"
export const GET_LEARNERS_LIST_SUCCESS = "GET_LEARNERS_LIST_SUCCESS"
export const GET_LEARNERS_LIST_FAIL = "GET_LEARNERS_LIST_FAIL"
