export const GETDISCOUNT = "GET_DISCOUNT";
export const GETDISCOUNTSUCCESS = "GET_DISCOUNT_SUCCESS";
export const GETDISCOUNTFALIURE = "GET_DISCOUNT_FALIURE";
export const ADDDISCOUNT = "ADD_DISCOUNT";
export const ADDDISCOUNTSUCCESS = "ADD_DISCOUNT_SUCCESS";
export const ADDDISCOUNTFALIURE = "ADD_DISCOUNT_FALIURE";
