/* GET CUSTOMERS */
export const GET_CUSTOMERS_LIST = "GET_CUSTOMERS_LIST"
export const GET_CUSTOMERS_LIST_SUCCESS = "GET_CUSTOMERS_LIST_SUCCESS"
export const GET_CUSTOMERS_LIST_FAIL = "GET_CUSTOMERS_LIST_FAIL"
